name: Publication CV

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checks-out du repo sous $GITHUB_WORKSPACE
            -   uses: actions/checkout@v3

            # Conversion adoc -> html
            -   name: asciidoctor-ghpages
                uses: manoelcampos/asciidoctor-ghpages-action@v2
                with:
                    pdf_build: true
                    ebook_main_adoc_file: cv
                    # asciidoctor_params: --attribute=nofooter
                    # adoc_file_ext: .ascii # default is .adoc
                    source_dir: src/ # default is .
                    # slides_build: true
                    # pre_build:
                    ## PDF_FILE est utilisé par l'action pour le push sur gh-pages
                    post_build: mv cv.html index.html; PDF_FILE=CV_Ludovic_RONSIN.pdf; mv ebook.pdf "$PDF_FILE"