name: Publication CV

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checks-out du repo sous $GITHUB_WORKSPACE
            -   uses: actions/checkout@v3
            # Positionne et formate la date de dernière maj du doc à la date de génération (Cf. docdatetime vs localdatetime)
            # pour prendre en compte n'importe quelle modification
            -   name: Set env
                run: echo "DOC_DATETIME=$(TZ=Europe/Paris date '+%d/%m/%Y&nbsp;%H:%M' )" >> $GITHUB_ENV

              # Conversion adoc -> html
            -   name: asciidoctor-ghpages
                uses: manoelcampos/asciidoctor-ghpages-action@v2
                with:
                    pdf_build: true
                    ebook_main_adoc_file: cv
                    #
                    asciidoctor_params: --attribute=docdatetime=${{ env.DOC_DATETIME }}
                    # adoc_file_ext: .ascii # default is .adoc
                    source_dir: src/ # default is .
                    # slides_build: true
                    ## Le passage d'attributs contenant des espaces par une variable de la ligne de commande (Cf. asciidoctor_params)  ne fonctionne pas bien.
                    ## Et le parsing de la CLI semble différent entre asciidoctor et asciidoctor-pdf
                    pre_build: "echo -e '${{ secrets.SECRETS_LOCAL }}' > secrets-local.asciidoc"
                    ## PDF_FILE est utilisé par l'action pour le push sur gh-pages
                    post_build: mv cv.html index.html; PDF_FILE=CV_Ludovic_Ronsin.pdf; mv ebook.pdf "$PDF_FILE"